### ISSUE TITLE
Issue adding this plugin to existing webpack v5

### ISSUE THREAD

**Issue by amiiit** [IvanRodriCalleja/emotion-swc-plugin#17]
Hello,

I tried to follow the install steps described here: basically npm install:

```
"emotion-swc-plugin": "^0.0.5",
```

and set the following to be my `swcrc`:
```
{
    "test": ".*.(js|jsx|ts(x?))$",
    "minify": false,
    "sourceMaps": true,
    "jsc": {
        "target": "es2016",
        "loose": true,
        "parser": {
            "syntax": "typescript",
            "tsx": true,
            "decorators": false,
            "dynamicImport": true
        },
        "transform": {
            "react": {
                "runtime": "automatic",
                "importSource": "@emotion/react",
                "useBuiltins": true,
                "refresh": true
            }
        },
        "experimental": {
                 "plugins": [ ["emotion-swc-plugin", {"sourceMap": false}] ]
           }
    },
    "env": {
        "targets": "last 2 versions, Firefox ESR, not IE 11, not op_mini all, not dead"
    }

}

```

Here's the webpack (v5) loader config:

```
{
    test: /\.(js|jsx|ts(x?))$/,
    exclude: /node_modules/,
    use: {
        loader: 'swc-loader',
        options: {
            parseMap: true,
        },
    },
}
```

I'm getting the following error:

```
ERROR in ./src/index.tsx
Module build failed (from ./node_modules/swc-loader/src/index.js):
Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/........../src/index.tsx")'

Caused by:
    0: Failed to create plugin instance
    1: Error while importing "env"."__lookup_char_pos_source_map_proxy": incompatible import type. Expected Function(FunctionType { params: [I32, I32], results: [I32] }) but received Function(FunctionType { params: [I32, I32, I32], results: [I32] })

Stack backtrace:
   0: _napi_register_module_v1
   1: _napi_register_module_v1
   2: _napi_register_module_v1
   3: _napi_register_module_v1
   4: _napi_register_module_v1
   5: _napi_register_module_v1
   6: _napi_register_module_v1
   7: _napi_register_module_v1
   8: <unknown>
   9: _worker
  10: __pthread_joiner_wake

Stack backtrace:
   0: _napi_register_module_v1
   1: _wasmer_vm_raise_trap
   2: <unknown>
   3: _worker
   4: __pthread_joiner_wake

ERROR in   Error: Child compilation failed:
  Module build failed (from ./node_modules/swc-loader/src/index.js):
  Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/....../server/index.html.js")'
  
  Caused by:
      0: Failed to create plugin instance
      1: Error while importing "env"."__lookup_char_pos_source_map_proxy": incompatible import type. Expected   Function(FunctionType { params: [I32, I32], results: [I32] }) but received Function(FunctionType { params:   [I32, I32, I32], results: [I32] })
  
  Stack backtrace:
     0: _napi_register_module_v1
     1: _napi_register_module_v1
     2: _napi_register_module_v1
     3: _napi_register_module_v1
     4: _napi_register_module_v1
     5: _napi_register_module_v1
     6: _napi_register_module_v1
     7: _napi_register_module_v1
     8: <unknown>
     9: _worker
    10: __pthread_joiner_wake
  
  Stack backtrace:
     0: _napi_register_module_v1
     1: _wasmer_vm_raise_trap
     2: <unknown>
     3: _worker
     4: __pthread_joiner_wake
  ModuleBuildError: Module build failed (from ./node_modules/swc-loader/src/index.js):
  Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'Some("/Users/...../server/index.html.js")'
  
  Caused by:
      0: Failed to create plugin instance
      1: Error while importing "env"."__lookup_char_pos_source_map_proxy": incompatible import type. Expected   Function(FunctionType { params: [I32, I32], results: [I32] }) but received Function(FunctionType { params:   [I32, I32, I32], results: [I32] })
  
  Stack backtrace:
     0: _napi_register_module_v1
     1: _napi_register_module_v1
     2: _napi_register_module_v1
     3: _napi_register_module_v1
     4: _napi_register_module_v1
     5: _napi_register_module_v1
     6: _napi_register_module_v1
     7: _napi_register_module_v1
     8: <unknown>
     9: _worker
    10: __pthread_joiner_wake
  
  Stack backtrace:
     0: _napi_register_module_v1
     1: _wasmer_vm_raise_trap
     2: <unknown>
     3: _worker
     4: __pthread_joiner_wake
      at processResult (/Users/...../node_modules/webp  ack/lib/NormalModule.js:758:19)
      at /Users/amit/workspace/code/github.com/ultimateai/dashboard-frontend/node_modules/webpack/lib/NormalM  odule.js:860:5
      at /Users/amit/workspace/code/github.com/ultimateai/dashboard-frontend/node_modules/webpack/node_module  s/loader-runner/lib/LoaderRunner.js:400:11
      at /Users/amit/workspace/code/github.com/ultimateai/dashboard-frontend/node_modules/webpack/node_module  s/loader-runner/lib/LoaderRunner.js:252:18
      at context.callback (/Users/amit/workspace/code/github.com/ultimateai/dashboard-frontend/node_modules/w  ebpack/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
      at /Users/amit/workspace/code/github.com/ultimateai/dashboard-frontend/node_modules/swc-loader/src/inde  x.js:95:25
  
  - NormalModule.js:758 processResult
    [dashboard-frontend]/[webpack]/lib/NormalModule.js:758:19
  
  - NormalModule.js:860 
    [dashboard-frontend]/[webpack]/lib/NormalModule.js:860:5
  
  - LoaderRunner.js:400 
    [dashboard-frontend]/[webpack]/[loader-runner]/lib/LoaderRunner.js:400:11
  
  - LoaderRunner.js:252 
    [dashboard-frontend]/[webpack]/[loader-runner]/lib/LoaderRunner.js:252:18
  
  - LoaderRunner.js:124 context.callback
    [dashboard-frontend]/[webpack]/[loader-runner]/lib/LoaderRunner.js:124:13
  
  - index.js:95 
    [dashboard-frontend]/[swc-loader]/src/index.js:95:25
  
  - child-compiler.js:169 
    [dashboard-frontend]/[html-webpack-plugin]/lib/child-compiler.js:169:18
  
  - Compiler.js:551 finalCallback
    [dashboard-frontend]/[webpack]/lib/Compiler.js:551:5
  
  - Compiler.js:577 
    [dashboard-frontend]/[webpack]/lib/Compiler.js:577:11
  
  - Compiler.js:1196 
    [dashboard-frontend]/[webpack]/lib/Compiler.js:1196:17
  
  
  - Hook.js:18 Hook.CALL_ASYNC_DELEGATE [as _callAsync]
    [dashboard-frontend]/[webpack]/[tapable]/lib/Hook.js:18:14
  
  - Compiler.js:1192 
    [dashboard-frontend]/[webpack]/lib/Compiler.js:1192:33
  
  - Compilation.js:2787 finalCallback
    [dashboard-frontend]/[webpack]/lib/Compilation.js:2787:11
  
  - Compilation.js:3092 
    [dashboard-frontend]/[webpack]/lib/Compilation.js:3092:11
  
  


1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.74.0 compiled with 3 errors in 1950 ms

```

Any idea what is happening or how could I fix that? Thank you !

**Comment by IvanRodriCalleja** [comment]
Hi sorry for the late response.

You should use https://github.com/swc-project/plugins/tree/main/packages/emotion as this is the oficial SWC emotion plugin.

I know there was a problem running SWC plugins in webpack but as i see the issue was closed 2 days ago: https://github.com/swc-project/plugins/issues/48

**Comment by amiiit** [comment]
Thanks for the response and sorry for the even later response from my side @IvanRodriCalleja 😆 .

We will have a look into the official plugin, thanks for the recommendation!
